version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" # Expõe a porta 6379 do Redis para acesso externo (opcional)
    networks:
      - flask_network

  flask_app_1:
    build: .
    container_name: flask_app_1
    ports:
      - "5001:5000"
    environment:
      - REDIS_HOST=redis # Conecta ao Redis usando o nome do serviço
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - flask_network

  flask_app_2:
    build: .
    container_name: flask_app_2
    ports:
      - "5002:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - flask_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Monta o arquivo de configuração do servidor
    depends_on:
      - flask_app_1
      - flask_app_2

    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
